services:
    postgres:
        image: postgres:${POSTGRES_VERSION}
        container_name: postgresql
        environment:
            - POSTGRES_DB=artifactory
            - POSTGRES_USER=artifactory
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "127.0.0.1:5432:5432"
        volumes:
            - ${ROOT_DATA_DIR}/postgres/var/data/postgres/data:/var/lib/postgresql/data
            - /etc/localtime:/etc/localtime:ro
        restart: always
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: 500M
        logging:
            driver: json-file
            options:
                max-size: "50m"
                max-file: "10"
        ulimits:
            nproc: 65535
            nofile:
                soft: 32000
                hard: 40000
        networks: 
          - jfrog

    artifactory:
        image: releases-docker.jfrog.io/jfrog/artifactory-oss:${ARTIFACTORY_VERSION}
        container_name: artifactory
        environment:
            - JF_ROUTER_ENTRYPOINTS_EXTERNALPORT=${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}
        volumes:
            - ${ROOT_DATA_DIR}/artifactory/var:/var/opt/jfrog/artifactory
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 8082:8082
            - 8081:8081
        restart: always
        logging:
            driver: json-file
            options:
                max-size: "50m"
                max-file: "10"
        deploy:
            resources:
                limits:
                    cpus: "2.0"
                    memory: 4G
        ulimits:
            nproc: 65535
            nofile:
                soft: 32000
                hard: 40000
        depends_on:
          - postgres
        networks: 
          - jfrog

    jenkins:
        image: jenkins/jenkins:${JENKINS_VERSION}
        container_name: jenkins
        privileged: true
        user: root
        ports:
         - 8080:8080
         - 50000:50000
        volumes:
            - ${ROOT_DATA_DIR}/jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - jfrog

    nginx:
        image: ${NGINX_VERSION}
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        restart: always
        extra_hosts: 
         - ${ARTIFACTORY_DOMAIN}:127.0.0.1
         - ${JENKINS_DOMAIN}:127.0.0.1
        depends_on:
         - jenkins
         - artifactory
        networks:
         - jfrog

networks:
  jfrog:
     driver: bridge